version: 2

jobs:
  build:
    # Override CIRCLE_WORKING_DIRECTORY (set to ~/project by default)
    working_directory: /home/agent/build
    docker:
      - image: docksal/ci-agent:php
    steps:
      # Inject build environment variables.
      # Each run statement runs in its own isolated shell (exported variables are not preserved).
      # $BASH_ENV can be used to pass environment variables between run statements.
      - run:
          name: Configure agent environment
          command: echo 'source build-env' > $BASH_ENV
      # Code checkout in the build agent
      - checkout
      # Run other commands
      - run:
          name: Other1 commands
          command: |
            build-exec 'pwd'
            build-exec 'cd ../../'
            build-exec 'pwd'
      # Launch a sandbox on the sandbox server
      - run:
          name: Build sandbox
          command: sandbox-init
      # Run other commands
      - run:
          name: Other2 commands
          command: |
            DEBUG=1 source build-env
            build-exec 'fin drush status'

workflows:
  version: 2
  default-workflow:
    jobs:
      - build
